title: Test Site
email: test@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple and elegant theme for Jekyll.
baseurl: "/parl-o-mate" # the subpath of your site, e.g. /blog/
url: "https://jonfoong.github.io/parl-o-mate" # the base hostname & protocol for your site
permalink: pretty

markdown: kramdown
